### ISSUE TITLE
jari moet dood right?

### ISSUE THREAD

**Issue by IcyPalm** [Jarinus/leertaak-5#21]
Eikel

**Comment by Jarinus** [comment]
Well, somebody's mad ^.^

**Comment by IcyPalm** [comment]
someone is being a hugeass enourmous Grammmar nazi

**Comment by Jarinus** [comment]
Someone is being a huge ass, enormous Grammar nazi.*

**Comment by goto-bus-stop** [comment]
huge-ass *

https://github.com/goto-bus-stop/xkcd-37
