### ISSUE TITLE
Single Measurement view

### ISSUE THREAD

**Issue by IcyPalm** [Jarinus/leertaak-5#41]
Create view for single measurement

**Comment by Jarinus** [comment]
Started on this issue in the 'singleMeasurementView' branch!

**Comment by Jarinus** [comment]
Created a basic view for this issue and included the route, as well as a basic controller. It can be used for reference.

**Comment by goto-bus-stop** [comment]
status? /cc @IcyPalm

**Comment by IcyPalm** [comment]
It is there and should be fine. Was implemented in 4623a73039efd0ed01ee6e8b2e6fc03a8bdc27b9

**Comment by IcyPalm** [comment]
- [ ]Add location chart

**Comment by IcyPalm** [comment]
Needs prettyfying

**Comment by jlsa** [comment]
Prettify by me?

**Comment by IcyPalm** [comment]
@jlsa Doe je ding!

**Comment by jlsa** [comment]
Oké, hij zat al in de master?

**Comment by IcyPalm** [comment]
jup

**Comment by jlsa** [comment]
top

**Comment by IcyPalm** [comment]
Done?

**Comment by jlsa** [comment]
@IcyPalm Voor zo ver ik het heb toegevoegd aan de measurement-design branch
