### ISSUE TITLE
Live updates for heatmaps & graphs

### ISSUE THREAD

**Issue by goto-bus-stop** [Jarinus/leertaak-5#48]
With checkboxes to toggle live updates. Will have to use polling unfortunately (unless we want to set up a websocket server…)

**Comment by jlsa** [comment]
I think for the purpose of this assignment polling will be good enough.

**Comment by IcyPalm** [comment]
@goto-bus-stop  Status?

**Comment by goto-bus-stop** [comment]
Implemented for heatmaps :v:
