### ISSUE TITLE
RainfallController#showMostRecent slowness

### ISSUE THREAD

**Issue by goto-bus-stop** [Jarinus/leertaak-5#49]
The RainfallController executes a query for every single station:

https://github.com/Jarinus/leertaak-5/blob/b7d427f/app/Http/Controllers/RainfallController.php#L63-L68

8000 queries take a long time. This should instead be 1 or 2 queries to fetch all stations _and_ their most recent measurement.

**Comment by Jarinus** [comment]
Werkende query: http://hastebin.com/ewiyebekax.sql
Succes ermee.
