### ISSUE TITLE
Secure Remote Password protocol implementation

### ISSUE THREAD

**Issue by jlsa** [Jarinus/leertaak-5#51]
Is the use of the SRP ( Secure Remote Password ) protocol something to implement next to SSL?

More info check out [SRP on Stanford.edu](http://srp.stanford.edu/)

**Comment by IcyPalm** [comment]
Is een interessant dingetje maar om dit voor dinsdag nog te implementeren is een beetje aan de late kant dus ik stel voor op dit te schrappen. 
Meningen van @goto-bus-stop, @tieskedh en @Jarinus ?

**Comment by jlsa** [comment]
I addressed this topic for the sake of the SLA. I'm closing this due to not a requirement.
