### ISSUE TITLE
Fake Measurement seeder

### ISSUE THREAD

**Issue by goto-bus-stop** [Jarinus/leertaak-5#6]
We need test data!

http://laravel.com/docs/5.1/seeding

Should:

 * Generate measurements across a 3 month period
 * Make some kind of sense, i.e. two subsequent measurements from 1 station should not differ wildly (we want nice graphs!)

I think the best way to do this is to

 1. generate measurements for only a few stations (maybe 10), and
 2. only generate measurements for every second for a few hours (24 hours of accurate measurements = ~85k measurements), and then drop down to a few measurements per hour for the rest of the 3 month period.

**Comment by jlsa** [comment]
Could the generator create database entries alter their timestamps and voila?

**Comment by goto-bus-stop** [comment]
Could, but if it's a Laravel Seeder, we can much much more easily refresh the entire DB, and we don't have to manually run the Java server & generator for N minutes.

I think we'd be looking at something like this to generate reasonable measurements:

```php
const AMOUNT_OF_STATIONS = 80; // for example
// initial measurement with somewhat reasonable randomly generated datums
$measurementData = [
  'temperature' => rand(-30, 30),
  // ...
];
foreach (range(1, 200000 /* should probably be a higher number */) as $n) {
    $measurementData = array_map(function ($value) {
        // value = value ± 15% (or a smaller variation)
        return $value + $value * (rand(-15, 15) / 100);
    }, $measurementData);

    /** <logic to increment time, +1 if $n is low, +more if $n is high> **/

    DB::table('measurements')->insert(array_merge(
        ['station' => $n % AMOUNT_OF_STATIONS + 1],
        $measurementData
    ));
}
```

I believe @IcyPalm volunteered last Friday to work on this, too
