### ISSUE TITLE
Page title minor issue

### ISSUE THREAD

**Issue by Jarinus** [Jarinus/leertaak-5#89]
The page title always displays as such:
'UNWDMI - ' + page name

On the login screen the page title is 'UNWDMI - ' for some reason.
Please add either 'Login portal' after it, or make the '-' optional.

**Comment by jlsa** [comment]
Fixed, new version is
``` 
<title>Weather Data Tool - Kyoto University - @yield('title')</title>
```

**Comment by Jarinus** [comment]
@jlsa Does not fix this issue. Read the issue again.

**Comment by jlsa** [comment]
Fix is part of kyoto-design branch
